name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.8'
          check-latest: true

      - name: Build Extension
        uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "go build -ldflags=\"-X main.version=${{ github.ref_name }}\" -o dist/"